<?php

namespace app\generators\crud\providers;

class DateProvider extends \schmunk42\giiant\base\Provider
{

    public function activeField($attribute)
    {
        if (isset($this->generator->getTableSchema()->columns[$attribute]) == FALSE) {
            return;
        }

        $column = $this->generator->getTableSchema()->columns[$attribute];

        if ($column->type !== 'date') {
            return;
        }

        $method = __METHOD__;
        return <<<EOS

// generated by {$method}
    \$form
    ->field(\$model, '{$column->name}')
    ->widget(\kartik\date\DatePicker::class, [
        'pluginOptions' => [
            'autoclose'=>true,
            'format' => 'yyyy-mm-dd'
        ],
    ])
;

EOS;
    }

    /**
     * Formatter for detail view attributes, who have get[..]ValueLabel function.
     *
     * @param $attribute ColumnSchema
     * @param $model ActiveRecord
     *
     * @return null|string
     */
    public function attributeFormat($attribute)
    {
        if (isset($this->generator->getTableSchema()->columns[$attribute]) == FALSE) {
            return;
        }

        $column = $this->generator->getTableSchema()->columns[$attribute];

        if ($column->type !== 'date') {
            return;
        }

        return <<<EOS
        [
                'attribute' => '{$attribute}',
                'format' => [
                    'datetime',
                    'format' => 'eeee, d MMMM Y',
                ],
            ]
EOS;
    }

    public function columnFormat($attribute, $model)
    {
        if (isset($this->generator->getTableSchema()->columns[$attribute]) == FALSE) {
            return;
        }

        $column = $this->generator->getTableSchema()->columns[$attribute];

        if ($column->type !== 'date') {
            return;
        }

        return <<<EOS

[
    'attribute' => '{$attribute}',
    'format' => [
        'datetime',
        'format' => 'eee, d MMM Y',
    ],
]
EOS;
    }
}